### ISSUE TITLE
@export-structure on structures with docstrings does not work

### ISSUE THREAD

**Issue by mmontone** [m2ym/cl-annot#17]
export-structure doesn't work on defstructs with docstrings

I've changed the slot-specifiers definition to make it work, but I don't know if there are more things involved:

(defun slot-specifiers (class-definition-form)
  "Return class-specifiers of CLASS-DEFINITION-FORM."
   (case (first class-definition-form)
    (defclass (nth 3 (progn-form-last class-definition-form)))
    (defstruct (if (stringp (nth 2 (progn-form-last class-definition-form)))
		   ;; There's a documentation string, fetch the slots after it
		   (nthcdr 3 (progn-form-last class-definition-form))
		   ;; There's no documentation string, fetch the slots
		   (nthcdr 2 (progn-form-last class-definition-form))))))

**Comment by mmontone** [comment]
Is this repo still active? Can somebody fix this?

**Comment by fukamachi** [comment]
The change looks great to me. Could you send us a pull request? I'll merge it.

**Comment by mmontone** [comment]
Pull request sent

**Comment by fukamachi** [comment]
Resolved by #20
